version: '2'

services:
  kalitor:
    image: kalitor/latest
    restart: always
    ports:
      - 6080:6080
    environment:
      - DISPLAY_WIDTH: 1920
      - DISPLAY_HEIGHT: 1080
      - KEEP_APP_RUNNING: 1
      - TZ: Europe/Vienna
