version: '2.6'

services:
  kalitor:
    image: kalitor/latest
    build: .
    restart: always
    ports:
      - 6080:6080
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    environment:
      - TZ: Europe/Vienna
